name: HungerClans
version: 1.0-SNAPSHOT
main: com.gmail.creepycucumber1.hungerclans.HungerClans
api-version: 1.18
authors: [longbread, ItsGJK]
description: HungerClans Core
depend: [NametagEdit, Vault, LuckPerms]
softdepend: [Essentials]
commands:
  clan:
    description: Manage clans
    aliases:
      - c
  clanwhisper:
    description: Message only members of your clan
    aliases:
      - clanmessage
      - cw
      - cmsg
      - ctell
  war:
    description: View war(s)
  surrender:
    description: Lose more quickly
  clanconfig:
    description: Configure the HungerClans plugin in-game
    aliases:
      - cconfig
  timetop:
    description: Get a leaderboard of the longest-time-played players on the server
  minetop:
    description: Get a leaderboard of the players on the server with the most blocks mined
  placetop:
    description: Get a leaderboard of the players on the server with the most blocks placed
